// Generated by scripts/generate-preview-messages.mjs - do not edit.
// Source: apps/web/app/i18n/{en,ja}.json (preview.* subset).
export const PREVIEW_MESSAGES = {
  en: {
    'preview.localBadge': 'Local preview',
    'preview.watching': 'Watching for changes',
    'preview.share': 'Share',
    'preview.annotateMode': 'Annotation mode',
    'preview.panelTitle': 'Comments',
    'preview.emptyHint':
      'Click any element to annotate it. Turn the toggle off to use links normally.',
    'preview.requestFixesOne': 'Request fixes ({n})',
    'preview.requestFixesOther': 'Request fixes ({n})',
    'preview.discardDrafts': 'Discard drafts',
    'preview.stateDraft': 'Draft',
    'preview.stateQueued': 'Queued',
    'preview.stateWorking': 'Fixing',
    'preview.stateResolved': 'Resolved',
    'preview.stateDismissed': 'Skipped',
    'preview.delete': 'Delete',
    'preview.reopen': 'Reopen',
    'preview.reopenNote':
      'Reopened annotations stay local until you submit them again.',
    'preview.batchWorkingOne': 'Agent is fixing {n} annotation',
    'preview.batchWorkingOther': 'Agent is fixing {n} annotations',
    'preview.elapsed': 'elapsed {time}',
    'preview.resolvedToastOne': 'Resolved {n} annotation',
    'preview.resolvedToastOther': 'Resolved {n} annotations',
    'preview.orphanNoticeOne':
      'The page changed a lot; {n} annotation lost its target',
    'preview.orphanNoticeOther':
      'The page changed a lot; {n} annotations lost their targets',
    'preview.orphanDiscard': 'Discard them',
    'preview.orphanKeep': 'Keep',
    'preview.you': 'You',
    'preview.agentName': 'Agent',
    'preview.inputPlaceholder': 'What should change?',
    'preview.cancel': 'Cancel',
    'preview.add': 'Add',
    'preview.corruptNotice':
      'Some saved annotations could not be read. The damaged file was set aside.',
    'preview.ended.title': 'Preview ended',
    'preview.ended.body': 'Annotations are saved. Run {command} to resume.',
    'preview.shareDialog.title': 'Share',
    'preview.shareDialog.destination': 'Destination',
    'preview.shareDialog.visibility': 'Visibility',
    'preview.shareDialog.notCarried':
      'Local annotations are not carried over. You can comment again after sharing.',
    'preview.shareDialog.snapshotNote':
      'Captured at {time}. Later changes are not included.',
    'preview.shareDialog.confirm': 'Share',
    'preview.shareDialog.cancel': 'Cancel',
    'preview.shareDialog.authRequired':
      'Sign in to share. Open the link below and approve this device.',
    'preview.shareDialog.authWaiting': 'Waiting for approval…',
    'preview.shareDialog.done': 'Shared',
    'preview.shareDialog.copy': 'Copy',
    'preview.shareDialog.copied': 'Copied',
    'preview.shareDialog.finish': 'Done',
    'preview.shareDialog.continue': 'Keep previewing',
    'preview.shareDialog.visibilityUnknown':
      'The audience could not be resolved from your config, so sharing is disabled. Fix the config and reopen this dialog.',
    'preview.shareDialog.visibilityAdjusted':
      'Shared with the {visibility} audience, which differs from your selection.',
    'preview.shareDialog.confirmDestination':
      'Signed in. Check the destination and audience, then share.',
    'preview.shareDialog.visibilityPrivate': 'Specific people',
    'preview.shareDialog.visibilityWorkspace': 'Everyone in this workspace',
    'preview.shareDialog.visibilityLink': 'Anyone with the link',
    'preview.shareDialog.visibilityProject': 'Project members',
    'preview.shareDialog.shareFailed': 'Sharing failed. Try again in a moment.',
    'preview.shareDialog.snapshotFailed':
      'The file could not be read, so sharing is disabled. Reopen this dialog once it is available.',
  },
  ja: {
    'preview.localBadge': 'ローカルプレビュー',
    'preview.watching': '変更を監視中',
    'preview.share': '共有する',
    'preview.annotateMode': 'コメントモード',
    'preview.panelTitle': 'コメント',
    'preview.emptyHint':
      '気になる要素をクリックしてコメント。リンクを操作したいときは右下のトグルでコメントモードを OFF',
    'preview.requestFixesOne': '修正を依頼する（{n} 件）',
    'preview.requestFixesOther': '修正を依頼する（{n} 件）',
    'preview.discardDrafts': '下書きを破棄',
    'preview.stateDraft': '下書き',
    'preview.stateQueued': '順番待ち',
    'preview.stateWorking': '修正中',
    'preview.stateResolved': '解決済み',
    'preview.stateDismissed': '見送り',
    'preview.delete': '削除',
    'preview.reopen': '差し戻す',
    'preview.reopenNote':
      '差し戻したコメントは、再度依頼するまでエージェントには届きません',
    'preview.batchWorkingOne': 'エージェントが {n} 件を修正中',
    'preview.batchWorkingOther': 'エージェントが {n} 件を修正中',
    'preview.elapsed': '経過 {time}',
    'preview.resolvedToastOne': '{n} 件を解決しました',
    'preview.resolvedToastOther': '{n} 件を解決しました',
    'preview.orphanNoticeOne':
      'ページが大きく変わったため {n} 件のコメントが対象を見失いました',
    'preview.orphanNoticeOther':
      'ページが大きく変わったため {n} 件のコメントが対象を見失いました',
    'preview.orphanDiscard': 'まとめて破棄',
    'preview.orphanKeep': '残す',
    'preview.you': 'あなた',
    'preview.agentName': 'エージェント',
    'preview.inputPlaceholder': 'どう直してほしい？',
    'preview.cancel': 'キャンセル',
    'preview.add': '追加',
    'preview.corruptNotice':
      '保存済みのコメントの一部を読み込めませんでした。壊れたファイルは退避済みです',
    'preview.ended.title': 'プレビューは終了しました',
    'preview.ended.body': 'コメントは保存済みです。{command} で再開できます',
    'preview.shareDialog.title': '共有する',
    'preview.shareDialog.destination': '宛先',
    'preview.shareDialog.visibility': '共有範囲',
    'preview.shareDialog.notCarried':
      'ローカルのコメントは共有先に持ち込まれません。共有後は共有先で新しくコメントできます',
    'preview.shareDialog.snapshotNote':
      '{time} 時点の内容です。それ以降の変更は含まれません',
    'preview.shareDialog.confirm': '共有する',
    'preview.shareDialog.cancel': 'キャンセル',
    'preview.shareDialog.authRequired':
      '共有にはログインが必要です。下のリンクを開いてこの端末を承認してください',
    'preview.shareDialog.authWaiting': '承認を待っています…',
    'preview.shareDialog.done': '共有しました',
    'preview.shareDialog.copy': 'コピー',
    'preview.shareDialog.copied': 'コピーしました',
    'preview.shareDialog.finish': '完了',
    'preview.shareDialog.continue': 'プレビューを続ける',
    'preview.shareDialog.visibilityUnknown':
      '設定から共有範囲を判定できなかったため、共有を停止しました。設定を直してからもう一度開いてください。',
    'preview.shareDialog.visibilityAdjusted':
      '選択した範囲ではなく {visibility} の共有範囲で共有されました。',
    'preview.shareDialog.confirmDestination':
      'ログインしました。宛先と共有範囲を確認してから共有してください。',
    'preview.shareDialog.visibilityPrivate': '個別共有',
    'preview.shareDialog.visibilityWorkspace': '社内全員',
    'preview.shareDialog.visibilityLink': 'リンクを知っている全員',
    'preview.shareDialog.visibilityProject': '関係者のみ',
    'preview.shareDialog.shareFailed':
      '共有に失敗しました。少し時間をおいて再試行してください。',
    'preview.shareDialog.snapshotFailed':
      'ファイルを読み取れないため共有できません。読み取れるようになってからこのダイアログを開き直してください。',
  },
} as const

export type PreviewMessageKey = keyof (typeof PREVIEW_MESSAGES)['en']
