#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"
mkdir -p png
PUBLIC="../../public"

# docs/brand/icon.svg is the single source for every brand mark. Run this after
# editing icon.svg to regenerate all derived assets (PNGs + the served files the
# app links to), so nothing drifts out of sync. Needs rsvg-convert + python3.

# Marketplace + OAuth consent screen sizes (120 = OAuth consent screen logo).
for size in 32 64 120 128 256 512; do
  rsvg-convert -w "$size" -h "$size" icon.svg -o "png/icon-${size}.png"
done

# Favicon + apple-touch sizes. The "as" tile stays legible down to 16px, so one
# source serves every size (no separate thick-stroke variant needed).
for size in 16 32 48 180; do
  rsvg-convert -w "$size" -h "$size" icon.svg -o "png/favicon-${size}.png"
done

# Served assets the app links to — kept in lockstep with icon.svg here. The OG
# card (apps/web/app/services/preview-image.server.ts) also points at apple-touch-icon.png
# rather than holding its own copy, so the logo never forks.
cp icon.svg "$PUBLIC/favicon.svg"
cp png/favicon-180.png "$PUBLIC/apple-touch-icon.png"

# favicon.ico: PNG-embedded ICO (16/32/48), no external icon tooling needed.
python3 - "$PUBLIC/favicon.ico" png/favicon-16.png png/favicon-32.png png/favicon-48.png <<'PY'
import struct, sys
out_path, *pngs = sys.argv[1:]
imgs = [(int(p.split('favicon-')[1].split('.')[0]), open(p, 'rb').read()) for p in pngs]
buf = bytearray(struct.pack('<HHH', 0, 1, len(imgs)))  # reserved, type=icon, count
offset = 6 + 16 * len(imgs)
for s, data in imgs:
    dim = s if s < 256 else 0
    buf += struct.pack('<BBBBHHII', dim, dim, 0, 0, 1, 32, len(data), offset)
    offset += len(data)
for _, data in imgs:
    buf += data
open(out_path, 'wb').write(buf)
PY

# OG card mark: the logo as an inline PNG data URI. satori renders data URIs
# without a runtime fetch (a worker can't reliably fetch its own origin), so the
# marketing Open Graph cards embed this instead. @generated here from the same
# icon.svg, so it never forks from the favicon.
python3 - ../../apps/web/app/services/brand-og-mark.generated.ts png/icon-128.png <<'PY'
import base64, sys
out_path, png_path = sys.argv[1:]
b64 = base64.b64encode(open(png_path, 'rb').read()).decode()
open(out_path, 'w').write(
    '// @generated by docs/brand/build.sh from docs/brand/icon.svg — do not edit.\n'
    '// The brand logo as an inline PNG data URI for the marketing Open Graph cards\n'
    "// (apps/web/app/services/preview-image.server.ts). satori draws it without a runtime\n"
    '// fetch, and regenerating from icon.svg keeps it in lockstep with the favicon.\n'
    'export const BRAND_OG_MARK =\n'
    f"  'data:image/png;base64,{b64}'\n"
)
PY

echo "Generated png/ + public/favicon.{svg,ico}, apple-touch-icon.png, brand-og-mark.generated.ts"
ls -la png/
