export function loader() {
  return { route: 'blog', title: 'Prerendered blog page' }
}

export default function Blog() {
  return (
    <main>
      <h1>Prerendered blog page</h1>
      <p>This page was generated by React Router.</p>
    </main>
  )
}
